### ISSUE TITLE
vue3.0中使用tsx好像没有效果，请问该如何配置下呢

### ISSUE THREAD

**Issue by MaoSkin** [wswmsword/postcss-mobile-forever#10]

**Comment by wswmsword** [comment]
方便给一个小 demo 吗，我看看，我也没用过 vue3 的 tsx

**Comment by MaoSkin** [comment]
[归档.zip](https://github.com/wswmsword/postcss-mobile-forever/files/11999791/default.zip)
帮忙看下

**Comment by MaoSkin** [comment]
> 
[归档.zip](https://github.com/wswmsword/postcss-mobile-forever/files/11999804/default.zip)
帮忙看下

**Comment by MaoSkin** [comment]
> > 
> 
> [归档.zip](https://github.com/wswmsword/postcss-mobile-forever/files/11999804/default.zip) 帮忙看下
