### ISSUE TITLE
The use of version Next.js is not effective.

### ISSUE THREAD

**Issue by usercao** [wswmsword/postcss-mobile-forever#16]
> Next.js version `14.0.3`

**Comment by wswmsword** [comment]
Ok，我回去看看。

**Comment by wswmsword** [comment]
你好，我把我的范例套在 Next.js 14.0.3 里试了一下，可以生效，您对比一下。
代码包下载：[nextjs-mobile-forever.zip](https://github.com/wswmsword/postcss-mobile-forever/files/13546001/nextjs-mobile-forever.zip)
查看 [`/example/nextjs` 代码](https://github.com/wswmsword/postcss-mobile-forever/tree/main/example/nextjs)

**Comment by wswmsword** [comment]
如果父级容器是 `#__next` 的话，要给 `#__next` 在样式文件里加个样式，PostCSS 插件实际上就扫描应用导入的样式文件，如果扫描到了对应的 class 就处理。

可以类似这样，或者就放一个空的样式：
```css
#__next {
  min-height: 100vh;
}
```

**Comment by usercao** [comment]
感谢🙏，明白了
