### ISSUE TITLE
unocss 的 @apply 指令写样式没有把 px 转换为 vw，正常写法是可以转换的

### ISSUE THREAD

**Issue by qiangguoguo** [wswmsword/postcss-mobile-forever#19]
[vite-project.zip](https://github.com/wswmsword/postcss-mobile-forever/files/13723124/vite-project.zip)
老哥麻烦看一下

**Comment by wswmsword** [comment]
需要您安装下 UnoCSS 的 PostCSS 插件：

```bash
npm add -D @unocss/postcss
```

PostCSS 配置文件中添加 UnoCSS 插件：

```diff
import mobile from 'postcss-mobile-forever'
import autoprefixer from 'autoprefixer'
+ import unocssPs from '@unocss/postcss';

export default () => {
  return {
    plugins: [
+       unocssPs(),
      autoprefixer(),
      mobile({
        // 页面最外层选择器，例如 “#app”，用于设置在桌面端和移动端横屏时的居中样式
        appSelector: '#app',
        // 应用基于该宽度进行开发，转换后的伸缩视图将会以该宽度的视图作为标准进行比例伸缩
        viewportWidth: (file) => file.includes("vant") ? 375 : 750,
        // 限制视口单位的最大宽度, 利用 min() 之类的 CSS 函数
        // maxDisplayWidth: 600,
        // 打开媒体查询模式，打开后将自动关闭 maxDisplayWidth
        enableMediaQuery: true,
      }),
    ],
  }
}

```

**Comment by wswmsword** [comment]
> 需要您安装下 UnoCSS 的 PostCSS 插件：
> 
> ```shell
> npm add -D @unocss/postcss
> ```
> 
> PostCSS 配置文件中添加 UnoCSS 插件：
> 
> ```diff
> import mobile from 'postcss-mobile-forever'
> import autoprefixer from 'autoprefixer'
> + import unocssPs from '@unocss/postcss';
> 
> export default () => {
>   return {
>     plugins: [
> +       unocssPs(),
>       autoprefixer(),
>       mobile({
>         // 页面最外层选择器，例如 “#app”，用于设置在桌面端和移动端横屏时的居中样式
>         appSelector: '#app',
>         // 应用基于该宽度进行开发，转换后的伸缩视图将会以该宽度的视图作为标准进行比例伸缩
>         viewportWidth: (file) => file.includes("vant") ? 375 : 750,
>         // 限制视口单位的最大宽度, 利用 min() 之类的 CSS 函数
>         // maxDisplayWidth: 600,
>         // 打开媒体查询模式，打开后将自动关闭 maxDisplayWidth
>         enableMediaQuery: true,
>       }),
>     ],
>   }
> }
> ```

UnoCSS 的 PostCSS 插件链接：https://unocss.dev/integrations/postcss

**Comment by qiangguoguo** [comment]
可以了，非常感谢
