### ISSUE TITLE
PostCSS报错

### ISSUE THREAD

**Issue by sunkebkn8** [wswmsword/postcss-mobile-forever#2]
![image](https://user-images.githubusercontent.com/66460612/221127780-de952554-7b46-4b2a-a89e-ad73d00598a4.png)
![image](https://user-images.githubusercontent.com/66460612/221127817-ed398204-b9fb-4940-939a-e0b0bf0cfa51.png)

vue2版本加vant，使用1.3.2能正常使用

**Comment by sunkebkn8** [comment]
> 嗯，1.3.2 不需要 PostCSS 8，试一下删除 node_modules 重新安装还报不报错，升级到 PostCSS 8 的版本（2.1.0）修复了桌面端 fixed 定位不准确的问题。
试了很多次不太行，postcss版本我也切换了几次

**Comment by wswmsword** [comment]
<img width="1512" alt="node_modules内postcss的版本" src="https://user-images.githubusercontent.com/26893092/221131226-f144163f-eceb-477c-8df4-fdf7228ccb5f.png">
这里的版本是多少？

**Comment by sunkebkn8** [comment]
![image](https://user-images.githubusercontent.com/66460612/221464126-4037ebb2-ed5a-4f06-bcf5-2ce2b7e0b0c9.png)
这个是版本号

**Comment by wswmsword** [comment]
看起来好像没什么问题，试一下删除 package-lock 和 node_modules，然后安装下面这个看看行不行。

```bash
npm install --save-dev postcss postcss-mobile-forever
```

**Comment by fdy696** [comment]
> 

1.3.2不存在

**Comment by fdy696** [comment]
![image](https://github.com/wswmsword/postcss-mobile-forever/assets/26914967/5703079a-16ef-4820-8536-4be34382093d)

**Comment by wswmsword** [comment]
> > 
> 
> 1.3.2不存在

@fdy696 对的，这个插件在 `2.1.2` 之前不叫 postcss-mobile-forever，是后来才改了名字。

您试一下安装最新的版本，最新版本是 `3.3.2`。我现在打不开 npm 官网，不然可以截个这个 postcss-mobile-forever 最小版本号的图。

**Comment by zhuweilong** [comment]
相同问题 也是报错 请问作者解决办法有么

**Comment by wswmsword** [comment]
@zhuweilong 你好，请问您是安装的 postcss-mobile-forever 吗，以前的 postcss-mobile-to-multi-displays 不在维护了，名字换成了 postcss-mobile-forever。

**Comment by zhuweilong** [comment]
@wswmsword 用的是最新的postcss-mobile-forever 你的demo vue 用的vite 你试试webpack node是10.19.0

**Comment by wswmsword** [comment]
@zhuweilong 我写了个 [Vue 的 webpack 例子](https://github.com/wswmsword/postcss-mobile-forever/tree/main/example/without-postcss-px-to-viewport/vue-webpack)，node 18.16.0 正常运行。我试了把 node 切到 10.19.0，有版本问题，你有在线的例子吗，我可以帮你调试看看，还是你就是要我这个例子的 node 10.19.0 的版本的？

**Comment by zhuweilong** [comment]
@wswmsword 你试试低版本的node10.19.0  因为相关关联的node-sass等 引入的依赖包都是以低版本node为标准的 vue2.6.11+vant2.12.47

**Comment by wswmsword** [comment]
@sunkebkn8 我写了依赖低版本 PostCSS（大于 v6.0.0）的 postcss-mobile-forever，按下面的命令安装应该不会报错“必须要求 PostCSS 8”了：

```bash
npm install postcss-mobile-forever@legacy --save-dev
```
