### ISSUE TITLE
有个nuxt3官网项目，准备同时适配PC和移动端，有插件相关demo参考下吗

### ISSUE THREAD

**Issue by xiang0308** [wswmsword/postcss-mobile-forever#23]

**Comment by wswmsword** [comment]
您可以参考下这个刚补充的 [Nuxt 范例](https://github.com/wswmsword/postcss-mobile-forever/tree/main/example/nuxtjs)。

**Comment by xiang0308** [comment]
> 您可以参考下这个刚补充的 [Nuxt 范例](https://github.com/wswmsword/postcss-mobile-forever/tree/main/example/nuxtjs)。

好的 谢谢~
