### ISSUE TITLE
配置include和exclude不生效

### ISSUE THREAD

**Issue by 983033995** [wswmsword/postcss-mobile-forever#24]
{
            appSelector: '#app',
            viewportWidth: 350,
            maxDisplayWidth: 600,
            include: [/\/pages\/index\//],
          }
包含和排除都不生效，使用postcss-px-to-viewport配置可以

**Comment by wswmsword** [comment]
方便截个配置截图吗

**Comment by 983033995** [comment]
![image](https://github.com/wswmsword/postcss-mobile-forever/assets/16315139/797945d2-66b4-4620-a892-84a306dfcc8f)

**Comment by 983033995** [comment]
同样的配置，我在新项目试了生效了，应该是这个项目配置的问题

**Comment by wswmsword** [comment]
可能是 mobile-forever 版本的问题，我在本地测也没啥问题

**Comment by wswmsword** [comment]
例子文件夹：https://github.com/wswmsword/postcss-mobile-forever/tree/main/example/cases/include

**Comment by 983033995** [comment]
好的，多谢

**Comment by Mrcxt** [comment]
<img width="248" alt="image" src="https://github.com/wswmsword/postcss-mobile-forever/assets/16064831/f10f92b6-9919-4231-96fb-8995138b2750">
我的也不生效。。。

**Comment by wswmsword** [comment]
什么版本的 mobile-forever，重新安装最新的版本有效吗？

**Comment by Mrcxt** [comment]
<img width="846" alt="image" src="https://github.com/wswmsword/postcss-mobile-forever/assets/16064831/4cbf040c-8912-4361-9514-e04d9a7f1c9b">
这是我的目录解构和配置。版本是 4.1.2。如果不配置include目前可以全量转换成vw，但是如果配置了，就一个都识别不到了，是不是我的正则写的不对
