### ISSUE TITLE
有个问题， 使用 vant-popup, 属性 是 bottom 的时候 在PC 端预览时不会 居中

### ISSUE THREAD

**Issue by AuYuHui** [wswmsword/postcss-mobile-forever#3]

**Comment by AuYuHui** [comment]
是的， 宽度占满屏幕了 

https://tinify.cn/backend/opt/output/zk4k532gdvh9g18nt5y13gg604bqt0wg/Snipaste_2023-03-06_16-41-22.jpg

**Comment by wswmsword** [comment]
好，知道了，近期我会修复。GitHub 这个评论框支持直接复制粘贴图片🙂。

**Comment by wswmsword** [comment]
**v2.3.3** 加了个参数，rootContainingBlockSelectorList，传入需要当成 fixed 定位的选择器就可以了。

<img width="803" alt="rootContainingBlockSelectorList" src="https://user-images.githubusercontent.com/26893092/223296389-7c08ce7c-7eb6-41ef-8759-546632b83e7d.png">
