### ISSUE TITLE
Vant4项目使用之后popup的mask半透明黑色背景不会宽度100%了

### ISSUE THREAD

**Issue by HanHuiOnLine** [wswmsword/postcss-mobile-forever#31]
![QQ图片20240409105317](https://github.com/wswmsword/postcss-mobile-forever/assets/22699483/70696060-9188-4a21-838f-b5ac95a678ae)
如上图所示，我尝试使用propertyBlackList属性，
` propertyBlackList: {
                        ".van-overlay": "width,left",
                    },`
但是"width,left"好像不能这么写，只能写一个。

**Comment by HanHuiOnLine** [comment]
使用数据的方式可以`propertyBlackList: [{ ".van-overlay": "width" }, { ".van-overlay": "left" }]`

**Comment by wswmsword** [comment]
您试试这样，貌似也行：

```
propertyBlackList: {
  ".van-overlay": ["width", "left"]
}
```

这样子更简洁一点，如果不行我加个这个写法。
