### ISSUE TITLE
`border` 属性的实现，用 `box-shadow` 去模拟是否会更合适

### ISSUE THREAD

**Issue by hooray** [wswmsword/postcss-mobile-forever#36]
目前设置开启 `border` 后，在暗黑模式下左右两侧会显示白边

<img width="480" alt="image" src="https://github.com/wswmsword/postcss-mobile-forever/assets/1574903/f27162ed-2924-44f0-9201-d162c3599ec2">

虽然可以设置改变颜色，但 border 会占用实际的空间，导致容器实际宽度会减 2px ，这应该是不符合预期的

<img width="534" alt="image" src="https://github.com/wswmsword/postcss-mobile-forever/assets/1574903/2b14ec2d-135b-4de5-b580-8fc346b72475">

而用 `box-shadow` 则不会占用实际的像素，就像这样：

```css
box-shadow: -1px 0 0 0 #ccc, 1px 0 0 0 #ccc;
```

**Comment by wswmsword** [comment]
这个问题改好了，发布在版本 4.1.3 里，打开 border 之后，现在会生成 `box-shadow: 0 0 0 1px #8888881f;`，移除了原来的 `border-left`、`border-right` 和 `box-sizing` 属性。
