### ISSUE TITLE
设置桌面端最大宽度

### ISSUE THREAD

**Issue by CoderBianer** [wswmsword/postcss-mobile-forever#37]
![image](https://github.com/wswmsword/postcss-mobile-forever/assets/68461702/423feee2-570e-4868-9f56-e8e7bf54290b)
你好，请问一下desktopWidth为600时如何设置桌面端最大宽度为375px。通过自定义媒体查询无法覆盖。

**Comment by wswmsword** [comment]
加一个这个属性试试，`minDesktopDisplayWidth: 375`

**Comment by CoderBianer** [comment]
解决了，谢谢！
desktopWidth: 375,
minDesktopDisplayWidth:640,
屏幕尺寸超出640时设置桌面最大宽度为375
