### ISSUE TITLE
color属性无效

### ISSUE THREAD

**Issue by webarn** [wswmsword/postcss-mobile-forever#4]
如: color: #781A05, 会经过转换变为: color: #781A5; 
最终浏览器不识别颜色代码, 造成无效

**Comment by wswmsword** [comment]
好的，我确认一下

**Comment by wswmsword** [comment]
> 如: color: #781A05, 会经过转换变为: color: #781A5; 最终浏览器不识别颜色代码, 造成无效

我尽快修复。

**Comment by wswmsword** [comment]
@webarn 颜色值包含数字可能会被转换的问题已修复，修复版本 v3.2.2。
