### ISSUE TITLE
支持行内样式的转换吗？

### ISSUE THREAD

**Issue by yanbowe** [wswmsword/postcss-mobile-forever#5]
支持行内PX样式的转换吗？

**Comment by wswmsword** [comment]
直接使用可能不行，如果放在 webpack 里，就是识别 css 文件，然后借 postcss 进行转换，但是行内样式所在的文件不会在识别范围内，不清楚有没有类似的插件可以识别行内样式，然后执行 postcss 插件。

**Comment by yanbowe** [comment]
好的，谢谢您的回答哦

**Comment by wswmsword** [comment]
不客气，我找到行内样式修改的办法之后在这里回复。

**Comment by yanbowe** [comment]
> 不客气，我找到行内样式修改的办法之后在这里回复。

好的，期待您的回复，我这边也找一下可实现方法
