### ISSUE TITLE
vite react ts 装了插件不会用 报错 求指教

### ISSUE THREAD

**Issue by CanonLs** [wswmsword/postcss-mobile-forever#55]
![Uploading 截屏2024-10-10 07.54.07.png…]()

**Comment by CanonLs** [comment]
<img width="670" alt="截屏2024-10-10 07 54 07" src="https://github.com/user-attachments/assets/be391f0b-8f80-4a79-bff8-13726b5caaa7">

**Comment by wswmsword** [comment]
方便给我发个包不，我本地看下

**Comment by CanonLs** [comment]
[归档.zip](https://github.com/user-attachments/files/17325608/default.zip)

**Comment by CanonLs** [comment]
麻烦帮忙看一下 谢谢啦  我的代码很垃圾  别笑！

**Comment by wswmsword** [comment]
我这边看好像没啥问题，`postcss.Plugin` 也是 `postcss.AcceptedPlugin` 的子类型。你截图报错“属性 prepare 的类型不兼容”，这个是句子全部吗？

<img width="1512" alt="type of postcss.plugins" src="https://github.com/user-attachments/assets/af8c298f-9c1f-422f-bd07-6a01434904d2">

**Comment by CanonLs** [comment]
不能将类型“Plugin”分配给类型“AcceptedPlugin”。
  不能将类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/postcss").Plugin”分配给类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/postcss").Plugin”。
    属性“prepare”的类型不兼容。
      不能将类型“((result: import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node...”分配给类型“((result: import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node...”。
        不能将类型“(result: import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node_...”分配给类型“(result: import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node_...”。
          参数“result”和“result” 的类型不兼容。
            不能将类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/....”分配给类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/....”。
              属性“lastPlugin”的类型不兼容。
                不能将类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/postcss").Plugin | import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/postcss").TransformCallback”分配给类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/postcss").Plugin | import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/postcss").TransformCallback”。
                  不能将类型“Plugin”分配给类型“Plugin | TransformCallback”。
                    不能将类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/postcss").Plugin”分配给类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/postcss").Plugin”。
                      属性“prepare”的类型不兼容。
                        不能将类型“((result: import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node...”分配给类型“((result: import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node...”。
                          不能将类型“(result: import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node_...”分配给类型“(result: import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node_...”。
                            参数“result”和“result” 的类型不兼容。
                              不能将类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/....”分配给类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/result").default<import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/document").default | import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/....”。
                                属性“lastPlugin”的类型不兼容。
                                  不能将类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/postcss").Plugin | import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/postcss").TransformCallback”分配给类型“import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/postcss").Plugin | import("/Users/canonls/Desktop/CanonLs/viteReact/node_modules/.pnpm/postcss@8.4.41/node_modules/postcss/lib/postcss").TransformCallback”。
                                    不能将类型“Plugin”分配给类型“Plugin | TransformCallback”。ts(2322)

**Comment by CanonLs** [comment]
额 我刚想了一下 你那边没问题 我这边有问题 唯一的变量就是node_module了。我把文件夹删了重新 install了 不报错了。。。。
真服了 可能有插件冲突了？ 因为我之前安装过 转换vw的插件

**Comment by CanonLs** [comment]
还想问个问题就是 行间样式没办法处理是吧

**Comment by wswmsword** [comment]
哈哈，重装 node_modules、重启 vs code、重启电脑，总有一个能好==

行内样式要套函数，这个插件没办法，因为插件只扫描 CSS 文件：

```javascript
/**
 * 限制大小的 vw 转换
 * @param {number} n
 * @param {number} idealWidth 理想宽度，设计稿的宽度
 * @param {number} maxWidth 表示伸缩视图的最大宽度
 */
export default function vw(n, idealWidth = 375, maxWidth = 600) {
  if (n === 0)
    return n

  const vwN = Math.round(n * 100 / idealWidth)
  const maxN = Math.round(n * maxWidth / idealWidth)
  const cssF = n > 0 ? 'min' : 'max'
  return `${cssF}(${vwN}vw, ${maxN}px)`
}
```

可以参考下上面这个，行内样式套就可以了，`vw(375)` 运行时变成 `min(100vw, 600px)`。或者可以用 [scale-view](https://github.com/wswmsword/scale-view) 这个库安装导入使用。

**Comment by CanonLs** [comment]
好嘞好嘞 多谢～
