### ISSUE TITLE
不明白为什么在 style 中写的 px 值在大屏下，会被转为NaN?

### ISSUE THREAD

**Issue by ren2436** [wswmsword/postcss-mobile-forever#6]
如题，这个怎么破解，是哪里配置有问题么？
![image](https://user-images.githubusercontent.com/8308372/232732558-4798a6f4-2b8e-4b7d-9eb5-580a37da9ec5.png)

![image](https://user-images.githubusercontent.com/8308372/232732976-3f417cd5-e501-452c-9619-f9400540b730.png)
![image](https://user-images.githubusercontent.com/8308372/232733035-eda8b842-3dd1-45d4-924a-80300494e313.png)

**Comment by wswmsword** [comment]
我不确定这个是不是之前版本的问题，可能要麻烦您升下最新版本，看看还有没有这个问题，我给你整了下新版本的配置：

```javascript
const autoprefixer = require('autoprefixer')
const viewport = require('postcss-mobile-forever')

const baseViewOpts = {
  rootSelector: "#app",
  viewportWidth: 750,
  unitPrecision: 3,
  propList: ['*'],
  selectorBlackList: ['.ignore', 'keep-px'],
  exclude: /node_modules(?![\\/]vant)/, // <---- 这里的 exclude 不能包括 vant，我看你下面要转换 vant 视图，这里排除 node_modules 所有文件之后 vant 应该也不会转换了
  border: true,
  disableDesktop: false,
  disableLandscape: false,
  mobileUnit: 'vw',
}

module.exports = {
  plugins: [
    autoprefixer(),
    viewport({
      ...baseViewOpts,
      viewportWidth: file => file.includes('node_modules/vant/') ? 375 : 750,
    })
  ]
}
```


重新卸载再重装就是最新版了：

```bash
npm uninstall postcss-mobile-forever
npm i postcss-mobile-forever --save-dev
```

如果还有问题我及时修复。

**Comment by ren2436** [comment]
[vite-vue3-test.zip](https://github.com/wswmsword/postcss-mobile-forever/files/11260394/vite-vue3-test.zip)
我使用最新版的搭建了一个最小的包，麻烦您看下，还是有这个问题
我这定位到是这行 出现的问题，注释掉就没问题了
viewportWidth: (file) => (file.includes('node_modules/vant/') ? 375 : 750),

**Comment by ren2436** [comment]
node版本为 18.14.2

**Comment by wswmsword** [comment]
> [vite-vue3-test.zip](https://github.com/wswmsword/postcss-mobile-forever/files/11260394/vite-vue3-test.zip) 我使用最新版的搭建了一个最小的包，麻烦您看下，还是有这个问题 我这定位到是这行 出现的问题，注释掉就没问题了 viewportWidth: (file) => (file.includes('node_modules/vant/') ? 375 : 750),

好，谢谢，我看下

**Comment by wswmsword** [comment]
@ren2436 已修复，修复版本是 `3.2.3` ^_^
