### ISSUE TITLE
使用rem模式vant的Toast会不居中

### ISSUE THREAD

**Issue by LUDA0831** [wswmsword/postcss-mobile-forever#62]
因为max-vw-mode的min函数兼容性有点差,想改成rem模式,修改之后发现toast不居中,max-vw-mode模式是正常的.

查看发现是.van-popup--center里面的margin:0 auto; 被编译成margin:0 123auto; 

使用[vue3-vant-mobile](https://github.com/easy-temps/vue3-vant-mobile)模板也复现了这个问题

![image](https://github.com/user-attachments/assets/ac6742b4-f97e-4929-839b-e67ddd040d7d)

**Comment by wswmsword** [comment]
版本 4.3.1 已修复，估计是写这边的时候睡着了。
