### ISSUE TITLE
启用unocss   class="w-343px h-140px"  px不会被转换为vw  有处理方案吗？

### ISSUE THREAD

**Issue by wuxingxi888** [wswmsword/postcss-mobile-forever#65]
![WechatIMG142](https://github.com/user-attachments/assets/665a3761-e86e-48ac-bbc6-aafd841e67da)

**Comment by wswmsword** [comment]
这种写法能看出来有没有走 PostCSS 吗。`w-343px` 这种在 UnoCSS 里有没有一个专有名词的叫法，我搜搜。

**Comment by wuxingxi888** [comment]
![WeChata00c35401fbb341a6a45cf9a2629ec8c](https://github.com/user-attachments/assets/da5a49f5-495c-4201-b6c5-f66d13dfcc6d)
![WeChat74ea68e87212667860170bb48c4d3a86](https://github.com/user-attachments/assets/d7a1856c-9107-4f02-80f3-86f55c5fac54)
看不出来 你试试 这种写法是指定px，  w-343 这种默认单位是rem

**Comment by wswmsword** [comment]
我用 [vue3-vant-mobile](https://github.com/easy-temps/vue3-vant-mobile) 这个项目试了下转换正常。

<img width="1489" alt="w-[343px] 的页面效果" src="https://github.com/user-attachments/assets/6fb2f539-a3fe-4fff-ab12-22c80e74d099" />
<img width="1489" alt="w-[343px] 的代码内容" src="https://github.com/user-attachments/assets/80f1cf80-4912-400d-90f8-50a5e1230904" />

**Comment by wswmsword** [comment]
这个是 vue3-vant-mobile 模版里的 unocss 配置文件链接：https://github.com/easy-temps/vue3-vant-mobile/blob/main/uno.config.ts

可能您可以对比参考下。

**Comment by wuxingxi888** [comment]
感谢 解决的 经排查 是postcss-mobile-forever 配置include导致的 修改完就好了。
![WeChatd5c8d74fb274d544f7c286022a798f40](https://github.com/user-attachments/assets/51e829f8-63f8-4a9e-a99c-191afd0fb74e)

**Comment by hooray** [comment]
我遇到了同样的问题，但是我必须设置 include，这种情况下有解决办法么？目前的兜底方案就是不使用unocss的写法
