### ISSUE TITLE
postcss-mobile-forever 报错要求依赖 PostCSS 8

### ISSUE THREAD

**Issue by wswmsword** [wswmsword/postcss-mobile-forever#8]
@wswmsword 你试试低版本的node10.19.0  因为相关关联的node-sass等 引入的依赖包都是以低版本node为标准的 vue2.6.11+vant2.12.47

_Originally posted by @zhuweilong in https://github.com/wswmsword/postcss-mobile-forever/issues/2#issuecomment-1560318986_

**Comment by wswmsword** [comment]
@zhuweilong 方便贴下 package.json 吗

**Comment by zhuweilong** [comment]
@wswmsword 
![image](https://github.com/wswmsword/postcss-mobile-forever/assets/42925903/04e6dbbc-26cd-48b1-8215-b78f656fa43b)
![image](https://github.com/wswmsword/postcss-mobile-forever/assets/42925903/b12a70a2-3ec0-4003-ac84-5be30606802c)

**Comment by wswmsword** [comment]
这两天比较忙，我会尽快看的。应该是只有版本号报错吧？有编译时候的报错吗？

**Comment by zhuweilong** [comment]
@wswmsword 本地开发就启动不起来

**Comment by wswmsword** [comment]
<img width="750" alt="PostCSS plugin postcss-mobile-forever requires PostCSS 8" src="https://github.com/wswmsword/postcss-mobile-forever/assets/26893092/6b1d6da8-e04b-404d-8fc8-d2b7559a351a">

是这样的报错吗

**Comment by zhuweilong** [comment]
@wswmsword 对的是这个

**Comment by wswmsword** [comment]
好的，我最近再写一个支持 PostCSS 8 之前版本的，发布之后通知你

**Comment by zhuweilong** [comment]
@wswmsword npm install postcss-mobile-forever@legacy --save-dev 这个可以使用 但是发现postcss-px-to-viewport selectorBlackList里定义的类  也会转换成vw单位

**Comment by wswmsword** [comment]
对，入参和 postcss-px-to-viewport 不共享的，可能 mobile-forever 先执行就先做了转换了，你可以把 px-to-viewport 的 selectorBlackList 也作为入参复制一份到 mobile-forever 里。

或者给我下您的 px-to-viewport 配置，我帮你转成 mobile-forever 的配置，就可以不用 px-to-viewport 了。
