### ISSUE TITLE
include是否有使用demo

### ISSUE THREAD

**Issue by yudan215** [wswmsword/postcss-mobile-forever#9]
使用vite vue 多页应用，如何只是mobile下面的文件才生效，配置了include: /mobile/,不起效果

**Comment by wswmsword** [comment]
是不是除了项目内，完整的本地路径里也包含 `mobile` 字符串，正则写的更精确一点试试看，我也写了个 [demo](https://github.com/wswmsword/postcss-mobile-forever/tree/main/example/cases/include)，试了下可以不转换非 mobile 文件夹内的样式，我这个正则对应了 pages 文件夹下的 mobile 文件夹：`/pages\/mobile\//`。
